# Generated by Django 5.1.3 on 2024-11-21 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swe33', '0002_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('buyerid', models.AutoField(db_column='BuyerID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=15, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('password', models.CharField(max_length=20)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'buyer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('deliveryid', models.AutoField(db_column='DeliveryID', primary_key=True, serialize=False)),
                ('deliverydate', models.DateField(blank=True, db_column='DeliveryDate', null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
            ],
            options={
                'db_table': 'delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farmid', models.AutoField(db_column='FarmID', primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=100, null=True)),
                ('size', models.DecimalField(blank=True, db_column='Size', decimal_places=2, max_digits=5, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
            ],
            options={
                'db_table': 'farm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('farmerid', models.AutoField(db_column='FarmerID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=15, null=True)),
                ('farmlocation', models.CharField(blank=True, db_column='FarmLocation', max_length=100, null=True)),
                ('password', models.CharField(max_length=20)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'farmer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(db_column='OrderID', primary_key=True, serialize=False)),
                ('orderdate', models.DateField(db_column='OrderDate')),
                ('orderstatus', models.CharField(blank=True, db_column='OrderStatus', max_length=20, null=True)),
                ('totalamount', models.DecimalField(blank=True, db_column='TotalAmount', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentid', models.AutoField(db_column='PaymentID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=2, max_digits=10, null=True)),
                ('paymentdate', models.DateField(blank=True, db_column='PaymentDate', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.AutoField(db_column='ProductID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderproduct',
            fields=[
                ('orderid', models.OneToOneField(db_column='OrderID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='swe33.order')),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
            ],
            options={
                'db_table': 'orderproduct',
                'managed': False,
            },
        ),
    ]
