# Generated by Django 5.1.3 on 2024-11-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swe33', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartid', models.AutoField(db_column='CartID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('status', models.CharField(blank=True, db_column='Status', max_length=11, null=True)),
                ('addeddate', models.DateTimeField(blank=True, db_column='AddedDate', null=True)),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chatid', models.AutoField(db_column='ChatID', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=6, null=True)),
                ('createdat', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
            ],
            options={
                'db_table': 'chat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageid', models.AutoField(db_column='MessageID', primary_key=True, serialize=False)),
                ('sendertype', models.CharField(db_column='SenderType', max_length=6)),
                ('messagetext', models.TextField(db_column='MessageText')),
                ('sentat', models.DateTimeField(blank=True, db_column='SentAt', null=True)),
            ],
            options={
                'db_table': 'message',
                'managed': False,
            },
        ),
    ]
